### ISSUE TITLE
ninja problem

### ISSUE THREAD

**Issue by poxiao0** [VinAIResearch/WaveDiff#11]
When I use the pretrained weights to test the result by a GPU on celeba_256 dataset, it occurs following preblem. I can not solve it, can you give me some advice?

Traceback (most recent call last):
  File "/home/wbx/anaconda3/envs/wavediff/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1723, in _run_ninja_build
    env=env)
  File "/home/wbx/anaconda3/envs/wavediff/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by quandao10** [comment]
I think you could try `pip install ninja`. If it is not working, try `conda install -c conda-forge cudatoolkit-dev`.

**Comment by poxiao0** [comment]
> I think you could try `pip install ninja`. If it is not working, try `conda install -c conda-forge cudatoolkit-dev`.

Thank you advice but these two advice are not valid. I can not resolve this problem.

**Comment by ZXXaaaa** [comment]
Hello, I meet the same problem. Have you solved this problem?

**Comment by poxiao0** [comment]
> Hello, I meet the same problem. Have you solved it?

Finally,I use the way from stylegan2. I suggest you to see its comments.

**Comment by ZXXaaaa** [comment]
OK, thanks for your answer.
